# Generated by Django 4.2.5 on 2023-10-08 10:10

import catalog.models
import catalog.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category_groups',
                'ordering': [models.OrderBy(models.F('weight'), nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='ExtraHTMLCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('head', 'Head'), ('body', 'Body')], default='head', max_length=20)),
                ('code', models.TextField(validators=[catalog.utils.code_validator])),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'head_or_body_html_codes',
                'ordering': [models.OrderBy(models.F('created_at'))],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_status', models.CharField(choices=[('done', 'Done'), ('new', 'New'), ('in_progress', 'In Progress'), ('failed', 'Failed')], default='new', max_length=20)),
                ('link', models.URLField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, unique=True, upload_to='images/%Y/%m/%d')),
                ('sha256', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('integer', 'Integer'), ('range', 'Range'), ('choice', 'Choice')], default='integer', max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sizes',
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_group', models.ForeignKey(default=catalog.models.CategoryGroup.get_default_pk, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.categorygroup')),
                ('sizes', models.ManyToManyField(blank=True, to='catalog.size')),
            ],
            options={
                'db_table': 'categories',
                'ordering': [models.OrderBy(models.F('weight'), nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='AutoPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_status', models.CharField(choices=[('done', 'Done'), ('new', 'New'), ('in_progress', 'In Progress'), ('failed', 'Failed')], default='new', max_length=20)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('sizes_values', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.category')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.image')),
            ],
            options={
                'db_table': 'auto_parts',
                'ordering': [models.OrderBy(models.F('number'))],
            },
        ),
    ]
