# Generated by Django 4.2.5 on 2023-10-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categorygroup',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
