# Generated by Django 4.2.5 on 2023-10-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_categorygroup_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='detailed_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
