services:
  web:
    build: ./docker/web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./database.env
      - ./web.env
